bounds:
  tau_ms:
   - 5.0
   - 200.0
  dend_threshold:
   - -70.0
   - -50.0
  # EC_weights_mean:
  #  - 0.05
  #  - 5.0
  EC_weights_std:
   - 0.05
   - 3.0
  SST_weights_std:
   - 0.05
   - 3.0
  SST_sf:
   - 5.0
   - 15.0

kwargs:
  data_root: '.'
  dend_threshold: -65.
  weight_config_dict:
    EC:
        dist_type: 'Lognormal'
        mean: 1.
        std: 1.
        sf: 1.
        sign: 1
    SST:
        dist_type: 'Equal'
        mean: 1.
        std: 1.
        sf: 10.
        sign: -1
    # NDNF:
    #     dist_type: 'Equal'
    #     mean: 1.
    #     std: 1.
    #     sign: -1
  n_cells_dict:
    EC:
      792
    SST:
      75
    NDNF:
      115
  make_it_spike: True
  tau_ms : 5.0
  dt: 0.001
  track_len: 180
  debug: False
  network_start_seed: 0
  num_network_seeds: 5
  export: False
  save_path: 'data'
  constant_vel: False
  include_beta: True
  flat_input: False
  store_intermediates: true ########################
  pkl_name: 'saved_data.pkl'
  store: mean 
  spikes: false
  epsps: true
  warp_axes: true
  network_start_seed: 0
  num_network_seeds: 5
  num_dendrites: 100
  # plot: False

stages:
  - source: ec_nested_stage_parallel
    get_args_static: get_args
    compute_features: compute_features
    filter_features: filter_features
    get_objectives: get_objectives
param_gen: PopulationAnnealing
param_gen_source: nested.optimize_utils
optimization_title: EC_SST_nested_number_6_velFbetaTinputF
x0:
  tau_ms: 50.0
  dend_threshold: -60.0
  EC_weights_std: 0.5
  SST_weights_std: 0.5
  SST_sf: 10.

  # inner_jobs: 7
  # network_start_seed: 0
  # ec_animal_average: True
  # vel_applied: real
  # use_averaged_velocity: 'actual_velocity' #"cell_type_av" 
  #  load: false
  #  use_model_EC: False
  #  weight_dist: Normal
  #  SST_bias_factor: 2.0
    # SST_bias_multi: 1.4
    #  real_vel: True
    #  store: mean   
    #  add_inh: 'neither'


  # warp_axes: true





