bounds:
  tau_ms:
   - 5.0
   - 200.0
  dend_threshold:
   - -70.0
   - -50.0
  weights_mean:
   - 0.05
   - 5.0
  weights_std:
   - 0.05
   - 3.0


kwargs:
  data_root: /Users/michaelfinch/CA1-interneuron-GLM
  animal: animal_3
  dend_threshold: -65.
  dist: 'Lognormal'
  make_it_spike: True
  tau_ms : 5.0
  dt_constant: 0.001
  dx: 3.6         
  debug: false
  seed_start: 0
  export: false
  save_path: /Users/michaelfinch/CA1-interneuron-GLM/Clean_notebooks_to_date/
  plot: true
  animal_by_animal: false 
  input_animal: 'animal_1'
  constant_vel: True
  include_beta: False
  flat_input: False
  optimization_time: true
  pkl_name: 'saved_data.pkl'
  load: false
  include_inh: false
  store: mean 
  spikes: false
  epsps: true
  warp_axes: true
  network_start_seed: 0
  num_network_seeds: 5



stages:
  - source: ec_nested_stage_parallel
    get_args_static: get_args
    compute_features: compute_features
    filter_features: filter_features
    get_objectives: get_objectives
param_gen: PopulationAnnealing
param_gen_source: nested.optimize_utils
optimization_title: EC_multidendrite_pop_anneal
x0:
  tau_ms: 50.0
  dend_threshold: -60.0
  weights_mean: 0.5
  weights_std: 0.5

